# Generated by Django 3.1.14 on 2023-06-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='Pokemons',
        ),
    ]
