# Generated by Django 4.2.4 on 2023-08-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_alter_pokemon_evolved_from_alter_pokemon_evolved_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_from',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_to',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_entity', to='pokemon_entities.pokemon'),
        ),
    ]
