# Generated by Django 4.2.4 on 2023-08-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_remove_pokemon_evolved_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolve',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_evolution', to='pokemon_entities.pokemon'),
        ),
    ]
