# Generated by Django 4.2.4 on 2023-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_remove_pokemon_evolve_pokemon_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Название покемона'),
        ),
    ]
