# Generated by Django 4.2.4 on 2023-08-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_alter_pokemon_description_alter_pokemon_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Что за покемон'),
        ),
    ]
