# Generated by Django 4.2.4 on 2023-08-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0022_alter_pokemon_description_alter_pokemon_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution',
            new_name='previous_evolution',
        ),
    ]
